navsat_transform:
  ros__parameters:
    frequency: 30.0
    delay: 3.0
    magnetic_declination_radians: 0.0 # For lat/long 55.944831, -3.186998
    yaw_offset: 0.0  # IMU reads 0 facing magnetic north, not east
    zero_altitude: true
    broadcast_utm_transform: true
    broadcast_utm_transform_as_parent_frame: true
    publish_filtered_gps: true
    use_odometry_yaw: true
    wait_for_datum: true
    datum: [49.9, 8.9, 0.0]

    